name: Clean Up Deployments on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  clean-up-deployments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: github-io-deployment
          fetch-depth: 0

      - name: Delete PR Deployment Directory
        run: |
          PR_NUMBER="PR-${{ github.event.pull_request.number }}"
          if [ -d "$PR_NUMBER" ]; then
            rm -rf "$PR_NUMBER"
            echo "Deleted folder: $PR_NUMBER"
          else
            echo "Folder $PR_NAME does not exist."
            exit 0
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Delete PR Deployment Directory"
          git push origin github-io-deployment
