name: Lint and Unit Tests

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm run lint > lintOutput.txt || true

      - name: Determine comment based on linting and test results
        id: comment
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          LINT_ERRORS=""
          if [ -f lintOutput.txt ]; then
              LINT_ERRORS=$(grep -E '[1-9][0-9]*\serror' lintOutput.txt || true)
          fi
          TEST_FAILED=false
          if [ -f testResult.txt ]; then
              TEST_FAILED=$(grep -q "TESTS_FAILED" testResult.txt && echo "true" || echo "false")
          fi
          if [ -n "$LINT_ERRORS" ] || [ "$TEST_FAILED" = "true" ]; then
            {
              echo 'PR_COMMENT<<EOF'
              echo "Checks failed. Here are the details:"
              if [ -n "$LINT_ERRORS" ]; then
                echo "Linting failed with the following errors:"
                echo "\`\`\`"
                cat lintOutput.txt
                echo "\`\`\`"
                echo "For more information on our linting policies, please see our [Linting-Guide](../tree/dev/Linting-Guide.md)."
              fi
              if [ "$TEST_FAILED" = "true" ]; then
                echo "Unit tests failed."
              fi
              echo EOF
            } >> "$GITHUB_OUTPUT"
          else
            echo "PR_COMMENT=Linting and unit tests succeeded" >> "$GITHUB_OUTPUT"
          fi

      - name: Fail if linting errors or unit tests failed
        if: steps.comment.outputs.PR_COMMENT != 'Linting and unit tests succeeded'
        run: exit 1

      - name: Comment on PR
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_COMMENT: ${{ steps.comment.outputs.PR_COMMENT }}
        run: |
          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "$PR_COMMENT"
          fi
