name: List Repositories

on:
  push:
    branches:
      - main

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
    # Step to checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step to update package list and install GitHub CLI
    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    # Step to authenticate GitHub CLI using a GitHub token
    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    # Step to list repositories in the specified organization
    - name: List repositories
      run: gh repo list avi-maniv92 --limit 100
