name: Example workflow for Python using Snyk
on: workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif

      - name: Print the Snyk SARIF file
        run: cat snyk.sarif

      - name: Total No. of Security Issues
        run: |
          length=$(cat snyk.sarif | jq '.runs[0].results | length')
          echo "Results_Length=$length" >> $GITHUB_ENV

      - name: Convert SARIF to CSV
        run: |
          python sarif_to_csv.py
